 
CREATE DATABASE MERCADO;

USE MERCADO;
 
 CREATE TABLE CLIENTES(
 ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(255) NOT NULL,
 TELEFONE VARCHAR(17)
 );
 
 CREATE TABLE PRODUTOS(
 ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(255) NOT NULL,
 PRECO DECIMAL(9,2) NOT NULL
 );
 
 INSERT INTO CLIENTES(NOME,TELEFONE)
	values("JONAS MADUREIRA","55 46 9 99345644"),
		  ("JOSE CRLOS RAMOS","55 46 9 98345494"),
		  ("LEONARDO FARIAS","55 46 9 993454238");
 
 INSERT INTO PRODUTOS(NOME,PRECO)
	values("Arroz Tio Joao",54.00),
		  ("Camiseta Nike",99.90),
		  ("Iogurte Nestle",5.50);
 
 
 CREATE TABLE PEDIDOS(
 ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 DATA_PEDIDO DATE NOT NULL,
 ID_CLIENTE INT NOT NULL,
 ID_PRODUTO INT NOT NULL,
 QUANTIDADE INT NOT NULL,
 TOTAL DECIMAL(10,2),
 
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
 );
 
 INSERT INTO PEDIDOS(DATA_PEDIDO, ID_CLIENTE, ID_PRODUTO, QUANTIDADE, TOTAL)
	VALUES ("2025-10-09", 1, 3, 2, 11.00);
 
 --- JOIN
 
 SELECT * FROM PEDIDOS
	JOIN CLIENTES ON PEDIDOS.ID_CLIENTE = CLIENTE.ID
	
SELECT
	PEDIDOS.ID,
	PEDIDOS.DATA_PEDIDO,
	PEDIDOS.ID_CLIENTE,
	CLIENTES.NOME,
	PEDIDOS.ID_PRODUTO,
	PRODUTOS.NOME,
	PEDIDOS.QUANTIDADE,
	PEDIDOS.TOTAL,
	(PEDIDOS.QUANTIDADE * PRODUTOS.PRECO) AS TOTAL
FROM PEDIDOS
	JOIN CLIENTES ON PEDIDOS.ID_CLIENTE = CLIENTES.ID
	JOIN PRODUTOS ON PEDIDOS.ID_PRODUTO = PRODUTOS.ID;

UPDATE PEDIDOS SET QUANTIDADE = 3;

